version: '3'

services:
  app:
    build:
      context: .
      args:
        FRONTEND_ENV: "REACT_APP_BACKEND_URL=http://localhost:8080/api"
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - ORIGINS=http://localhost:8080,http://192.168.50.167:8080
      - DB_NAME=shooting_matches_db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge