version: '3'

services:
  app:
    build:
      context: .
      args:
        FRONTEND_ENV: "REACT_APP_BACKEND_URL=http://localhost:8080/api"
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=shooting_matches_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: